name: heroku-jupyter
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # bind notebook version (compatibility to pgcontents)
  - notebook=5.* # 7.22 failed, 6.* fails because pgcontents expects notebook.services to be there, 5.* fails due to size. And get get package locally.
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython
  # bind tornado version (websocket problems)
  - tornado
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip
  - pip:
    - pgcontents
    - git+https://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
