#!/usr/bin/env bash


# pgcontents init -l $DATABASE_URL --no-prompt

jupyter contrib nbextension install --user
jupyter nbextensions_configurator enable --user

# jupyter notebook \
# 	--no-browser --no-mathjax --ip=* --port $PORT --allow-root\
# 	$JUPYTER_NOTEBOOK_ARGS \
# 	notebooks

jupyter lab \
	--no-browser --ip='0.0.0.0' --port $PORT --allow-root\
	$JUPYTER_NOTEBOOK_ARGS \
	notebooks
